export const inspirationalPhrases = [
  "Entrenar hoy es invertir en tu energia de manana.",
  "Un poco mejor que ayer ya cuenta.",
  "Empieza fuerte, termina orgulloso.",
  "La constancia gana cuando la motivacion baja.",
  "Tu cuerpo escucha cada decision que tomas.",
  "Hoy toca sumar una victoria pequena.",
  "No necesitas ganas, necesitas empezar.",
  "Cada repeticion te acerca a tu version mas fuerte.",
  "Hazlo simple, hazlo bien, hazlo hoy.",
  "El progreso se construye en dias como este.",
  "Entrena por la persona que estas construyendo.",
  "Hoy puedes mas de lo que crees.",
  "La disciplina tambien se entrena.",
  "No rompas la cadena: mueve el cuerpo.",
  "Tu cuerpo puede soportar casi cualquier cosa, es a tu mente a la que tienes que convencer",
  "El dolor es temporal, el orgullo es para siempre.",
  "No pares cuando estes cansado, para cuando hayas terminado.",
  "El unico mal entrenamiento es el que no sucedio.",
  "Cada dia es una nueva oportunidad para mejorar.",
  "El exito es la suma de pequenos esfuerzos repetidos dia tras dia.",
  "No cuentes los dias, haz que los dias cuenten.",
  "El sudor es solo grasa llorando.",
  "No se trata de ser el mejor, se trata de ser mejor que ayer.",
  "El cuerpo logra lo que la mente cree.",
];
